version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Containers
    ports:
      - "8000:80"

  actorsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Containers
      - ASPNETCORE_URLS=http://*:8002
      - ServiceConfig__ServiceDiscoveryAddress=http://consulservice:8500
      - ServiceConfig__ServiceAddress=http://actorsapi
      - ServiceConfig__ServiceName=actors
      - ServiceConfig__ServiceId=v1
    ports:
      - "0.0.0.0:8002:80"

  moviesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Containers
      - ASPNETCORE_URLS=http://*:8001
      - ServiceConfig__ServiceDiscoveryAddress=http://consulservice:8500
      - ServiceConfig__ServiceAddress=http://moviesapi
      - ServiceConfig__ServiceName=movies
      - ServiceConfig__ServiceId=v1
    ports:
      - "0.0.0.0:8001:80"

  authapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Containers
      - ASPNETCORE_URLS=http://*:8003
      - ServiceConfig__ServiceDiscoveryAddress=http://consulservice:8500
      - ServiceConfig__ServiceAddress=http://authapi
      - ServiceConfig__ServiceName=auth
      - ServiceConfig__ServiceId=v1
    ports:
      - "0.0.0.0:8003:80"

  rabbitmq:
    ports:
        - '5672:5672'
        - '15672:15672'

  consulservice:
    ports:
      - "8500:8500"