apiVersion: v1
kind: Service
metadata:
  labels:
    app: actorsapi
  name: actorsapi
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 80
  selector:
    app: actorsapi
status:
  loadBalancer: {}
