apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authapi
  name: authapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Containers
        - name: ASPNETCORE_URLS
          value: http://*:8003
        - name: ServiceConfig__ServiceAddress
          value: http://authapi:8003
        - name: ServiceConfig__ServiceDiscoveryAddress
          value: http://consulservice:8500
        - name: ServiceConfig__ServiceId
          value: v1
        - name: ServiceConfig__ServiceName
          value: auth
        image: authapi:latest
        imagePullPolicy: IfNotPresent
        name: authapi
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
