apiVersion: v1
kind: Service
metadata:
  labels:
    app: authapi
  name: authapi
spec:
  ports:
  - name: "8003"
    port: 8003
    targetPort: 80
  selector:
    app: authapi
status:
  loadBalancer: {}
